// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRlf01s9ylxX0s6xJVwzt5zpWy6vKHKM',
    appId: '1:864659463307:web:797b8a702659f783e7c88e',
    messagingSenderId: '864659463307',
    projectId: 'lostandfound-b9baa',
    authDomain: 'lostandfound-b9baa.firebaseapp.com',
    storageBucket: 'lostandfound-b9baa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0hr7OVEVbv729J7dHkIALJO1IYeNGYIg',
    appId: '1:864659463307:android:2c64c0f5e7a5eb56e7c88e',
    messagingSenderId: '864659463307',
    projectId: 'lostandfound-b9baa',
    storageBucket: 'lostandfound-b9baa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLdcp27xOvIVsEKR82Mlfm1YQ4u_9lWZM',
    appId: '1:864659463307:ios:24993e06b9d0f5ffe7c88e',
    messagingSenderId: '864659463307',
    projectId: 'lostandfound-b9baa',
    storageBucket: 'lostandfound-b9baa.appspot.com',
    iosClientId: '864659463307-9t2j26lm8n6707319q7p8s4n0cs24qdd.apps.googleusercontent.com',
    iosBundleId: 'it.fabc.lostAndFound',
  );
}
